---
ingress:
  type: bool
  help: |-
    Render ingresses.yaml from Template?
    Say "no" for multiple and / or complicated ingresses.

ingClass:
  when: "{{ ingress }}"
  type: str
  choices:
    internal: nginx-crt-house
    external: nginx-external

ingSvcName:
  when: "{{ ingress }}"
  type: str
  default: "{% if svcName != '' %}{{ svcName }}{% else %}{{ name }}{% endif %}"

ingSvcPortNum:
  when: "{{ ingress }}"
  type: int

ingHost:
  when: "{{ ingress }}"
  type: str
  default: "{{ name }}.crt.{% if ingress.class == 'nginx-external' %}lol{% else %}house{% endif %}"
  help: ingress hostname

ingCname:
  when: "{%if ingress and ingress.class == 'nginx-external' %}true{% endif %}"
  type: str
  help: ingress cname (only if accessible externally!)

ingWebSockets:
  when: "{{ ingress }}"
  type: bool
  help: enable web sockets on ingress
  default: no

ingExtraAnnotations:
  when: "{{ ingress }}"
  type: str
  multiline: true

ingPathType:
  when: "{{ ingress }}"
  type: str
  choices:
    Prefix: Prefix
    ImplementationSpecific: ImplementationSpecific
    Exact: Exact
