---
ingName:
  when: "{{ ingress }}"
  type: str
  default: "{{ name }}"

ingClass:
  when: "{{ ingress }}"
  type: str
  choices:
    internal: nginx-crt-house
    external: nginx-external

ingHost:
  when: "{{ ingress }}"
  type: str
  default: "{{ name }}.crt.{% if ingClass == 'nginx-external' %}lol{% else %}house{% endif %}"
  help: ingress hostname

ingCname:
  when: "{% if ingress and ingClass == 'nginx-external' %}true{% endif %}"
  type: str
  help: ingress cname (only if accessible externally!)

ingWebSockets:
  when: "{{ ingress }}"
  type: bool
  help: enable web sockets on ingress
  default: no

homepageEnabled:
  when: "{{ ingress }}"
  type: bool
  default: yes

homepageName:
  when: "{{ homepageEnabled }}"
  type: str
  default: "{{ name }}"

homepageDescription:
  when: "{{ homepageEnabled }}"
  type: str

homepageGroup:
  when: "{{ homepageEnabled }}"
  type: str

homepageIcon:
  when: "{{ homepageEnabled }}"
  type: str
  default: "{{ homepageName | lower }}"

ingExtraAnnotations:
  when: "{{ ingress }}"
  type: str
  multiline: true

ingPathType:
  when: "{{ ingress }}"
  type: str
  choices:
    Prefix: Prefix
    ImplementationSpecific: ImplementationSpecific
    Exact: Exact

ingSecret:
  type: str
