labels:
  type: str
  help: Kustomization commonLabels
  multiline: true
  default: "app: {{ name }}"

configmap:
  type: bool
  help: Include configmaps.yaml in Kustomization.

deployment:
  type: bool
  help: Include deployments.yaml in Kustomization.

externalsecret:
  type: bool
  help: Include external-secrets.yaml in Kustomization.

ingress:
  type: bool
  help: Include ingresses.yaml in Kustomization.

pvc:
  type: bool
  help: Include pvcs.yaml in Kustomization.

recurringJobs:
  type: bool
  help: Include Longhorn RecurringJobs backup-jobs.yaml in Kustomization.
  when: "{{ pvc }}"

service:
  type: bool
  help: Include services.yaml in Kustomization.

sts:
  type: bool
  help: Include statefulsets.yaml in Kustomization.

additionalResources:
  type: str
  help: Comma-separated list of additional resources to append to Kustomization.resources.
  placeholder: certificates.yaml,crds.yaml,rbac.yaml etc
