---
labels:
  type: str
  help: Kustomization commonLabels
  multiline: true
  default: "app: {{ name }}"

reloader:
  type: bool
  help: Enable reloader annotation? (Probably yes if using configmaps, external-secrets, or secrets)
  default: no
