name: run svu then templatron

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: svu
        id: svu
        uses: charlesthomas/github-action-svu@v1.0.6+2.2.0
        with:
          clone: true
          pushTag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run Templatron
        if: ${{ steps.svu.outputs.changed }}
        uses: addnab/docker-run-action@v3
        env:
          GIT_AUTHOR_EMAIL: ch@rlesthom.as
          GIT_AUTHOR_NAME: Charles Thomas
          GIT_COMMITTER_EMAIL: ch@rlesthom.as
          GIT_COMMITTER_NAME: Charles Thomas
          TTTKN: ${{ secrets.TTTKN }}
        with:
          registry: ghcr.io
          image: ghcr.io/charlesthomas/templatron:0.4.59
          options: -e TTTKN -e GIT_AUTHOR_EMAIL -e GIT_AUTHOR_NAME -e GIT_COMMITTER_EMAIL -e GIT_COMMITTER_NAME
          run: |
            mkdir -p /Users/crthomas/code
            /venv/bin/poetry run templatron --token-variable-name TTTKN --clone-root /Users/crthomas/code/charlesthomas charlesthomas/homelab-template update
