name: run svu then templatron

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: svu
        id: svu
        uses: charlesthomas/github-action-svu@v0.10.0-1.12.0
        with:
          clone: true
          forcePatchIncrement: true
          pushTag: true
  templatron:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: run Templatron
        uses: addnab/docker-run-action@v3
        env:
          GIT_AUTHOR_EMAIL: ch@rlesthom.as
          GIT_AUTHOR_NAME: Charles Thomas
          GIT_COMMITTER_EMAIL: ch@rlesthom.as
          GIT_COMMITTER_NAME: Charles Thomas
          TTTKN: ${{ secrets.TTTKN }}
        with:
          registry: ghcr.io
          image: ghcr.io/charlesthomas/templatron:0.4.3
          options: -e TTTKN -e GIT_AUTHOR_EMAIL -e GIT_AUTHOR_NAME -e GIT_COMMITTER_EMAIL -e GIT_COMMITTER_NAME
          run: |
            mkdir -p /home/crthomas/code
            /venv/bin/poetry run templatron --token-variable-name TTTKN --clone-root /home/crthomas/code/charlesthomas charlesthomas/homelab-template update
