name: run svu then templatron

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: svu
        id: svu
        uses: obfu5c8/action-svu@v1
        with:
          force-increment: true
      - name: tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.svu.outputs.version }}`,
              sha: context.sha
            })
      - uses: addnab/docker-run-action@v3
        env:
          GIT_AUTHOR_EMAIL: ch@rlesthom.as
          GIT_AUTHOR_NAME: Charles Thomas
          GIT_COMMITTER_EMAIL: ch@rlesthom.as
          GIT_COMMITTER_NAME: Charles Thomas
          TTTKN: ${{ secrets.TTTKN }}
        with:
          registry: ghcr.io
          image: ghcr.io/charlesthomas/templatron:0.4.3
          options: -e TTTKN -e GIT_AUTHOR_EMAIL -e GIT_AUTHOR_NAME -e GIT_COMMITTER_EMAIL -e GIT_COMMITTER_NAME
          run: |
            mkdir -p /Users/crthomas/code
            /venv/bin/poetry run templatron --token-variable-name TTTKN --clone-root /Users/crthomas/code charlesthomas/homelab-template update
