name: Run Templatron

on:
  workflow_run:
    workflows: ["Version with svu"]
    type:
      - completed

jobs:
  templatron:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: ghcr.io/charlesthomas/templatron:0.4.3
          options: --workdir /Users/crthomas/code
          run: |
            /venv/bin/poetry run templatron charlesthomas/homelab-template update
