name: run svu

on:
  push:
    branches:
      - main

jobs:
  svu:
    runs-on: ubuntu-latest
    steps:
      - name: svu
        id: svu
        uses: charlesthomas/github-action-svu@v1.0.2+1.12.0
        with:
          clone: true
          pushTag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
