name: run templatron

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'tmpl/**'

jobs:
  templatron:
    runs-on: ubuntu-latest
    steps:
      - name: run Templatron
        if: ${{ steps.svu.outputs.changed }}
        uses: addnab/docker-run-action@v3
        env:
          GIT_AUTHOR_EMAIL: ch@rlesthom.as
          GIT_AUTHOR_NAME: Charles Thomas
          GIT_COMMITTER_EMAIL: ch@rlesthom.as
          GIT_COMMITTER_NAME: Charles Thomas
          TTTKN: ${{ secrets.TTTKN }}
        with:
          registry: ghcr.io
          image: ghcr.io/charlesthomas/templatron:0.4.17
          options: -e TTTKN -e GIT_AUTHOR_EMAIL -e GIT_AUTHOR_NAME -e GIT_COMMITTER_EMAIL -e GIT_COMMITTER_NAME
          run: |
            mkdir -p /home/crthomas/code
            /venv/bin/poetry run templatron --token-variable-name TTTKN --clone-root /home/crthomas/code/charlesthomas charlesthomas/homelab-template update
